# Generated by Django 3.1.7 on 2021-03-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bedroom',
            new_name='bedrooms',
        ),
    ]
